### ISSUE TITLE
Base64 v1.0 - недостатки выявленные при работе в b4351 x86 и x64

### ISSUE THREAD

**Issue by VictorVG** [Maximus5/FarPlugins#3]
При работе с данным плагином выявлено несколько неприятных эффектов с общей причиной - если в текстовом файле плагин при его запуске из панелей видит сигнатуру Base64, то он пытается его декодировать и тут будет два результата - или сообщение об ошибке как описано в http://forum.ru-board.com/topic.cgi?forum=5&topic=31718&start=6400#7 и или второй, более неприятный эффект - при наличии в комплекте плагинов плагина FarHints v1.20 наблюдаем падение Far с кодом ошибки 0x80000003 если попытаться открыть в редакторе файл base64.cpp.

Я думаю что стоит отключить в плагине вход в архивы по Enter и поставить ограничение на длину декодируемой строки т.к. у себя я получил падение машине с ОЗУ 8 Гб (ЦП Core 2 Duo E8500 / m/b MSI P45D3 Platinum на P45 + ICH10R / 4 \* 2 GB DDR3-1333 / GTX 650) с Вин7 х64. Ну, случай номер два конечно во многом спорный в смысле поиска виновника ибо им может оказаться и FarHints, но ранее у меня он вызывал падение Far либо в случае если присутствовал субплагин Text, либо коли по каким-то причинам не мог писать в свою БД настроек. На него хватает баг-репортов, но проблемы с Base64 выплыли совсем неожиданно...

Сам плагин штука полезная, но вот про эти недостатки хочется забыть....

**Comment by VictorVG** [comment]
Плагин пришлось исключить из списка используемых, хотя он и нужен - с момента создания инца почти два года, а исправлений пока мы не придумали...

**Comment by VictorVG** [comment]
@Maximus5 

Т.е. как я понимаю эксперимент с Base64 признан неудачным и стоит использовать иное решение чем данный плагин?:)

**Comment by Maximus5** [comment]
Ну, вы же и так его не используете, да и исправления вы за два года не придумали.

Текущая функциональность лично меня устраивает.

**Comment by VictorVG** [comment]
Возможности устраивают всех, вопрос в неисправленном баге в коде плагина:

> **Victor_VG**
> Скажите, пожалуйста, а что у вас назначено для .txt-файлов при нажатии Enter?
> Раньше в этом случае файл открывался в текстовом редакторе Windows, который назначен по умолчанию, у меня это Bred3. Сейчас имею то, что представлено на скрине.
> 
> P.S. Ваша сборка FarUE3 x64.
> 
> ![screenshot](https://cloud.githubusercontent.com/assets/906886/22217540/6c8a00f8-e1b4-11e6-8216-4447a095dd7f.png)

> **wseventeen**
> 
> **Victor_VG**
> 
> > Это сбой БД истории после b4344 так проявляется.
> 
> Это вряд ли. Даже фаза луны в этом случае более вероятная причина,
> не говоря уже об одном из огромного набора дополнений ацкой мега сборки.
>   
> Добавлено:
> 
> Гугл по тексту ошибки находит виновника
> 
>  - ошибка в коде https://github.com/Maximus5/FarPlugins/blob/master/Base64/src/Base64.cpp
