### ISSUE TITLE
Вопрос - что такое новый плагин "Played in LightAllow" и как и где им управлять? 

### ISSUE THREAD

**Issue by VictorVG** [Maximus5/FarPlugins#7]
С гита получил его исходники, собрал в VC14 v140_xp_toolkit, в х86 и AMD64 вариантах, положил вместе с .lng в каталог плагинов, отстроил колонку, но как плагин настраивается и где применим не понял. Можно попросить в этом подсказку? Вот что у меня скомпилилось - [**alloy_c0.zip**](https://github.com/Maximus5/FarPlugins/files/847716/alloy_c0.zip) (за отстутствием VC12 воспользовался VC14). 

Плагин заинтересовл тем, что и сам LA пользуюсь, вот и стало интересно а что позного мы можем использовать?

**Comment by Maximus5** [comment]
Этот "новому" плагин, которому года три уже, есть обыкновенный C0 плагин. Пометка в панелях файлов из *.lap.

**Comment by VictorVG** [comment]
Идею уловил
